name: yearprogress

on:
  workflow_dispatch:
  schedule:
    - cron: "1 2 3 * *"

jobs:
  yearprogress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - run: go run main.go
        env:
          MASTODON_SERVER: ${{secrets.MASTODON_SERVER}}
          MASTODON_CLIENT_ID: ${{secrets.MASTODON_CLIENT_ID}}
          MASTODON_CLIENT_SECRET: ${{secrets.MASTODON_CLIENT_SECRET}}
          MASTODON_ACCESS_TOKEN: ${{secrets.MASTODON_ACCESS_TOKEN}}
          MASTODON_USERNAME: ${{secrets.MASTODON_USERNAME}}
          MASTODON_PASSWORD: ${{secrets.MASTODON_PASSWORD}}
