name: yearprogress

on:
  workflow_dispatch:
  schedule:
    - cron: "1 3 */5 * *"

jobs:
  yearprogress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - run: go run main.go
